name: CI

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION : '3.10'
  LIBRARY_NAME: 'ansys-api-dyna'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  build-library:
    name: "Build library"
    runs-on: ubuntu-latest
    steps:
      - uses: pyansys/actions/build-library@v4
        with:
          library-name: ${{ env.LIBRARY_NAME }}

  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: "Release to the private PyPI"
        uses: pyansys/actions/release-pypi-private@v4
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          twine-username: "__token__"
          twine-token: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}

      - name: "Release to the public PyPI"
        uses: pyansys/actions/release-pypi-public@v4
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          twine-username: "__token__"
          twine-token: ${{ secrets.PYPI_TOKEN }}

      - name: "Release to GitHub"
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            ${{ env.LIBRARY_NAME }}-artifacts/*.whl
            ${{ env.LIBRARY_NAME }}-artifacts/*.tar.gz
